from typing import List, Optional
from .core.soc_detector import detect_soc
from .generators.lattice_generator import make_sunny_latvecs_block
from .generators.atom_generator import make_sunny_atoms_block
from .generators.exchange_generator import make_sunny_exchange_block
from .generators.dipole_generator import make_sunny_dipole_block
from .generators.relax_generator import make_relax_block

def build_sunny_julia(exchange_path: str,
                      soc_mode: str = "auto",
                      mag_threshold: float = 0.5,
                      j_tol: float = 1e-3,
                      d_tol: float = 1e-3,
                      dist_tol: float = 1e-3,
                      max_dist: float = 0.0,
                      min_exchange: float = 1e-3,
                      with_dipole: bool = False,
                      with_relax: bool = False,
                      spins: Optional[List[str]] = None) -> str:
    if soc_mode == "soc":
        is_soc = True
    elif soc_mode == "no-soc":
        is_soc = False
    else:
        is_soc = detect_soc(exchange_path)

    parts: List[str] = []
    parts += [
        "# Autogenerated from TB2J exchange.out",
        "using Sunny",
        "using LinearAlgebra",
        "using GLMakie",
        "units = Units(:meV, :angstrom)",
        f"# Detected SOC mode: {'SOC (non-collinear)' if is_soc else 'no SOC (collinear)'}",
        "",
        make_sunny_latvecs_block(exchange_path),
        "",
        make_sunny_atoms_block(exchange_path,
                               mag_threshold=mag_threshold,
                               is_soc=is_soc,
                               spins=spins),
        "",
        make_sunny_exchange_block(exchange_path,
                                  mag_threshold=mag_threshold,
                                  j_tol=j_tol, d_tol=d_tol, dist_tol=dist_tol,
                                  max_dist=max_dist, min_exchange=min_exchange,
                                  use_dmi=is_soc,
                                  spins=spins),
    ]

    if with_dipole:
        parts += ["", make_sunny_dipole_block(exchange_path,
                                                mag_threshold=mag_threshold,
                                                is_soc=is_soc)]
    if with_relax:
        parts += ["", make_relax_block()]

    return "\n".join(parts)
